spring:
  config:
    import: optional:file:.env[.properties]

  application:
    name: BE_Picobox
  datasource:
    url: jdbc:oracle:thin:@picobox_medium
    username: ADMIN
    password: ${ADB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      data-source-properties:
        oracle.net.tns_admin: ${TNS_ADMIN}
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.OracleDialect
  mail:
    protocol: smtp
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    test-connection: true
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 100MB

  cloud:
    aws:
      region:
        static: ap-northeast-2
      s3:
        bucket: picobox-bucket
      credentials:
        access-key: ${AWS_ACCESS_KEY_ID}
        secret-key: ${AWS_SECRET_ACCESS_KEY}
springdoc:
  override-with-generic-response: false
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method
    urls:
      - name: Java Annotations API
        url: /v3/api-docs
      - name: Custom OpenAPI YAML
        url: /swagger/openapi.yaml