spring:
  application:
    name: BE_Picobox
  datasource:
    url: jdbc:oracle:thin:@picobox_medium
    username: ADMIN
    password: ${ADB_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver
    hikari:
      data-source-properties:
        oracle.net.tns_admin: ${TNS_ADMIN}
      connection-test-query: SELECT 1 FROM DUAL
  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  override-with-generic-response: false
  swagger-ui:
    tags-sorter: alpha
    operations-sorter: method