openapi: 3.0.1
info:
  title: BE_Picobox
  version: 1.0.0

tags:
  - name: 관리자 - 02. 배우 관리
    description: 배우 정보 CRUD API (관리자용)

paths:
  /api/admin/actors/create-with-image:
    post:
      tags:
        - 관리자 - 02. 배우 관리
      summary: 배우 정보 및 프로필 이미지 동시 등록
      description: |
        새로운 배우 정보(JSON 'actorDetails')와 프로필 이미지 파일('profileImage')을
        한 번의 요청으로 등록합니다.
        Content-Type: multipart/form-data
      requestBody:
        required: true
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                actorDetails:
                  type: string
                  description: JSON string of ActorRequestDto (as raw text, not file)
                  example: |
                    {
                      "name": "정우성",
                      "birthDate": "1972-04-22",
                      "biography": "대한민국 배우입니다."
                    }
                profileImage:
                  type: string
                  format: binary
                  description: 프로필 이미지 파일 (선택 사항)
      responses:
        '201':
          description: 배우 정보와 이미지가 성공적으로 등록되었습니다.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ActorResponseDto'
        '400':
          description: |
            잘못된 요청입니다 (예: 유효성 검사 실패, 중복 배우 등)
        '500':
          description: 서버 오류 또는 파일 업로드 실패입니다.

components:
  schemas:
    ActorResponseDto:
      type: object
      properties:
        id:
          type: integer
        name:
          type: string
        birthDate:
          type: string
          format: date
        bio:
          type: string
        profileImageUrl:
          type: string
          format: uri